-- Group 32
-- Members:
-- Chia Yong Peng
-- Victor Lua
-- Yeong Poon

-- Generated by Oracle SQL Developer Data Modeler 21.4.1.349.1605
--   at:        2022-04-23 19:50:27 JST
--   site:      Oracle Database 12c
--   type:      Oracle Database 12c

-- Capture run of script in file called 
-- wc_schema_output.txt
set echo on
SPOOL wc_schema_output.txt

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE country CASCADE CONSTRAINTS;

DROP TABLE cruise CASCADE CONSTRAINTS;

DROP TABLE cruise_port CASCADE CONSTRAINTS;

DROP TABLE language CASCADE CONSTRAINTS;

DROP TABLE manifest CASCADE CONSTRAINTS;

DROP TABLE operator CASCADE CONSTRAINTS;

DROP TABLE pass_port_tour CASCADE CONSTRAINTS;

DROP TABLE passenger CASCADE CONSTRAINTS;

DROP TABLE port CASCADE CONSTRAINTS;

DROP TABLE ship CASCADE CONSTRAINTS;

DROP TABLE temperature CASCADE CONSTRAINTS;

DROP TABLE tour CASCADE CONSTRAINTS;

DROP TABLE tour_available CASCADE CONSTRAINTS;

-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE TABLE cabin (
    cabin_class    CHAR(1) NOT NULL,
    ship_code      NUMBER(3) NOT NULL,
    cabin_code     CHAR(3) NOT NULL,
    cabin_num      NUMBER(3) NOT NULL,
    cabin_capacity NUMBER(5) NOT NULL
);

ALTER TABLE cabin
    ADD CONSTRAINT chk_cabinclass CHECK ( cabin_class IN ( 'B', 'I', 'O', 'S' ) );

COMMENT ON COLUMN cabin.cabin_class IS
    'cabin class';

COMMENT ON COLUMN cabin.ship_code IS
    'ship code';

COMMENT ON COLUMN cabin.cabin_code IS
    'cabin code';

COMMENT ON COLUMN cabin.cabin_num IS
    'cabin number';

COMMENT ON COLUMN cabin.cabin_capacity IS
    'cabin capacity';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cabin_class );

CREATE TABLE country (
    country_code CHAR(2) NOT NULL,
    country_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN country.country_code IS
    'country code';

COMMENT ON COLUMN country.country_name IS
    'country name';

ALTER TABLE country ADD CONSTRAINT country_pk PRIMARY KEY ( country_code );

CREATE TABLE cruise (
    cruise_id   NUMBER(4) NOT NULL,
    cruise_name VARCHAR2(20) NOT NULL,
    cruise_desc VARCHAR2(100) NOT NULL,
    ship_code   NUMBER(3) NOT NULL
);

COMMENT ON COLUMN cruise.cruise_id IS
    'cruise id';

COMMENT ON COLUMN cruise.cruise_name IS
    'cruise name';

COMMENT ON COLUMN cruise.cruise_desc IS
    'cruise description';

COMMENT ON COLUMN cruise.ship_code IS
    'ship code';

ALTER TABLE cruise ADD CONSTRAINT cruise_port_pk PRIMARY KEY ( cruise_id );

CREATE TABLE cruise_port (
    cp_id                      NUMBER(4) NOT NULL,
    cruise_port_arrival_time   DATE NOT NULL,
    cruise_id                  NUMBER(4) NOT NULL,
    port_code                  CHAR(5) NOT NULL,
    cruise_port_departure_time DATE
);

COMMENT ON COLUMN cruise_port.cp_id IS
    'cruise port id';

COMMENT ON COLUMN cruise_port.cruise_port_arrival_time IS
    'Arrival time';

COMMENT ON COLUMN cruise_port.cruise_id IS
    'cruise id';

COMMENT ON COLUMN cruise_port.port_code IS
    'port code';

COMMENT ON COLUMN cruise_port.cruise_port_departure_time IS
    'Departure time';

ALTER TABLE cruise_port ADD CONSTRAINT cruise_port_pkv1 PRIMARY KEY ( cp_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_nk UNIQUE ( cruise_port_arrival_time,
                                           port_code,
                                           cruise_id );

CREATE TABLE language (
    lang_code CHAR(2) NOT NULL,
    lang_name VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN language.lang_code IS
    'language code';

COMMENT ON COLUMN language.lang_name IS
    'Language Name';

ALTER TABLE language ADD CONSTRAINT language_pk PRIMARY KEY ( lang_code );

CREATE TABLE manifest (
    cabin_class CHAR(1) NOT NULL,
    cruise_id   NUMBER(4) NOT NULL,
    manifest_id NUMBER(4) NOT NULL,
    pass_id     NUMBER(5) NOT NULL
);

COMMENT ON COLUMN manifest.cabin_class IS
    'cabin class';

COMMENT ON COLUMN manifest.cruise_id IS
    'cruise id';

COMMENT ON COLUMN manifest.manifest_id IS
    'manifest id';

COMMENT ON COLUMN manifest.pass_id IS
    'Passenger ID';

ALTER TABLE manifest ADD CONSTRAINT manifest_pk PRIMARY KEY ( manifest_id );

ALTER TABLE manifest ADD CONSTRAINT manifest_nk UNIQUE ( cabin_class,
                                                         cruise_id );

CREATE TABLE operator (
    op_id   NUMBER(5) NOT NULL,
    op_name VARCHAR2(20) NOT NULL,
    op_ceo  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN operator.op_id IS
    'operator id';

COMMENT ON COLUMN operator.op_name IS
    'operator name';

COMMENT ON COLUMN operator.op_ceo IS
    'operator chief executive officer name';

ALTER TABLE operator ADD CONSTRAINT operator_pk PRIMARY KEY ( op_id );

CREATE TABLE pass_port_tour (
    ppt_no           NUMBER(4) NOT NULL,
    tp_no            NUMBER NOT NULL,
    pass_id          NUMBER(5) NOT NULL,
    cruise_id        NUMBER(4) NOT NULL,
    payment_received CHAR(1) NOT NULL
);

ALTER TABLE pass_port_tour
    ADD CONSTRAINT chk_paymentreceived CHECK ( payment_received IN ( 'N', 'Y' ) );

COMMENT ON COLUMN pass_port_tour.ppt_no IS
    'passenger port tour number';

COMMENT ON COLUMN pass_port_tour.tp_no IS
    'tour port number';

COMMENT ON COLUMN pass_port_tour.pass_id IS
    'Passenger ID';

COMMENT ON COLUMN pass_port_tour.cruise_id IS
    'cruise id';

COMMENT ON COLUMN pass_port_tour.payment_received IS
    'Payment received';

CREATE UNIQUE INDEX pass_port_tour__idx ON
    pass_port_tour (
        tp_no
    ASC );

ALTER TABLE pass_port_tour ADD CONSTRAINT pass_port_tour_pk PRIMARY KEY ( ppt_no );

ALTER TABLE pass_port_tour
    ADD CONSTRAINT pass_port_tour_nk UNIQUE ( cruise_id,
                                              pass_id,
                                              tp_no );

CREATE TABLE passenger (
    pass_id       NUMBER(5) NOT NULL,
    pass_fname    VARCHAR2(20),
    pass_lname    VARCHAR2(20),
    pass_gender   CHAR(1) NOT NULL,
    pass_dob      DATE NOT NULL,
    pass_street   VARCHAR2(15) NOT NULL,
    pass_town     VARCHAR2(15) NOT NULL,
    pass_postcode NUMBER(4) NOT NULL,
    pass_country  CHAR(2) NOT NULL,
    pass_phone    NUMBER(15) NOT NULL,
    lang_code     CHAR(2) NOT NULL,
    pass_id1      NUMBER(5) NOT NULL
);

ALTER TABLE passenger
    ADD CONSTRAINT chk_passgender CHECK ( pass_gender IN ( 'F', 'M' ) );

COMMENT ON COLUMN passenger.pass_id IS
    'Passenger ID';

COMMENT ON COLUMN passenger.pass_fname IS
    'Passenger first name';

COMMENT ON COLUMN passenger.pass_lname IS
    'Passenger last name';

COMMENT ON COLUMN passenger.pass_gender IS
    'Passenger gender';

COMMENT ON COLUMN passenger.pass_dob IS
    'Passenger date of birth';

COMMENT ON COLUMN passenger.pass_street IS
    'Passenger street';

COMMENT ON COLUMN passenger.pass_town IS
    'Passenger town';

COMMENT ON COLUMN passenger.pass_postcode IS
    'Passenger post code';

COMMENT ON COLUMN passenger.pass_country IS
    'Passenger country';

COMMENT ON COLUMN passenger.pass_phone IS
    'Passenger phone';

COMMENT ON COLUMN passenger.lang_code IS
    'language code';

COMMENT ON COLUMN passenger.pass_id1 IS
    'Passenger ID';

ALTER TABLE passenger ADD CONSTRAINT passenger_pk PRIMARY KEY ( pass_id );

CREATE TABLE port (
    port_code       CHAR(5) NOT NULL,
    country_code    CHAR(2) NOT NULL,
    port_name       VARCHAR2(20) NOT NULL,
    port_population NUMBER(8) NOT NULL,
    port_longitude  NUMBER(9, 6) NOT NULL,
    port_latitude   NUMBER(8, 6) NOT NULL
);

COMMENT ON COLUMN port.port_code IS
    'port code';

COMMENT ON COLUMN port.country_code IS
    'country code';

COMMENT ON COLUMN port.port_name IS
    'port name';

COMMENT ON COLUMN port.port_population IS
    'port population';

COMMENT ON COLUMN port.port_longitude IS
    'port longitude';

COMMENT ON COLUMN port.port_latitude IS
    'port latitude';

ALTER TABLE port ADD CONSTRAINT port_pk PRIMARY KEY ( port_code );

CREATE TABLE ship (
    ship_code     NUMBER(3) NOT NULL,
    op_id         NUMBER(5) NOT NULL,
    ship_name     VARCHAR2(10) NOT NULL,
    ship_com_date DATE NOT NULL,
    ship_tonnage  NUMBER(6) NOT NULL,
    ship_capacity NUMBER(4) NOT NULL,
    ship_country  VARCHAR2(20) NOT NULL
);

COMMENT ON COLUMN ship.ship_code IS
    'ship code';

COMMENT ON COLUMN ship.op_id IS
    'operator id';

COMMENT ON COLUMN ship.ship_name IS
    'ship name';

COMMENT ON COLUMN ship.ship_com_date IS
    'ship commission date';

COMMENT ON COLUMN ship.ship_tonnage IS
    'ship tonnage';

COMMENT ON COLUMN ship.ship_capacity IS
    'ship capacity';

COMMENT ON COLUMN ship.ship_country IS
    'ship country';

ALTER TABLE ship ADD CONSTRAINT ship_pk PRIMARY KEY ( ship_code );

CREATE TABLE temperature (
    temp_month DATE NOT NULL,
    port_code  CHAR(5) NOT NULL,
    temp_low   NUMBER(2) NOT NULL,
    temp_high  NUMBER(2) NOT NULL
);

COMMENT ON COLUMN temperature.temp_month IS
    'monthly average temperature';

COMMENT ON COLUMN temperature.port_code IS
    'port code';

COMMENT ON COLUMN temperature.temp_low IS
    'average low temperature';

COMMENT ON COLUMN temperature.temp_high IS
    'average high temperature';

ALTER TABLE temperature ADD CONSTRAINT temperature_pk PRIMARY KEY ( temp_month,
                                                                    port_code );

CREATE TABLE tour (
    tour_no       NUMBER(3) NOT NULL,
    tour_name     VARCHAR2(20) NOT NULL,
    tour_desc     VARCHAR2(20) NOT NULL,
    tour_hour     NUMBER(2) NOT NULL,
    tour_cost     NUMBER(9, 2) NOT NULL,
    tour_min_pass NUMBER(3) NOT NULL,
    tour_wchair   CHAR(1) NOT NULL,
    tour_avail    CHAR(3) NOT NULL
);

ALTER TABLE tour
    ADD CONSTRAINT chk_tourwchair CHECK ( tour_wchair IN ( 'N', 'Y' ) );

ALTER TABLE tour
    ADD CONSTRAINT chk_touravailability CHECK ( tour_avail IN ( 'DAI', 'FRI', 'MON', 'SAT',
    'SUN',
                                                                'THU', 'TUE', 'WED', 'WKD',
                                                                'WKE' ) );

COMMENT ON COLUMN tour.tour_no IS
    'tour number ';

COMMENT ON COLUMN tour.tour_name IS
    'tour name';

COMMENT ON COLUMN tour.tour_desc IS
    'tour description';

COMMENT ON COLUMN tour.tour_cost IS
    'tour cost';

COMMENT ON COLUMN tour.tour_min_pass IS
    'minimum number of passenger';

COMMENT ON COLUMN tour.tour_wchair IS
    'tour wheel chair';

COMMENT ON COLUMN tour.tour_avail IS
    'tour available';

ALTER TABLE tour ADD CONSTRAINT tour_pk PRIMARY KEY ( tour_no );

CREATE TABLE tour_available (
    tp_no     NUMBER(4) NOT NULL,
    port_code CHAR(5) NOT NULL,
    tour_no   NUMBER(3) NOT NULL,
    tour_date DATE NOT NULL,
    ppt_no    NUMBER NOT NULL
);

COMMENT ON COLUMN tour_available.tp_no IS
    'tour port number';

COMMENT ON COLUMN tour_available.port_code IS
    'port code';

COMMENT ON COLUMN tour_available.tour_no IS
    'tour number ';

COMMENT ON COLUMN tour_available.tour_date IS
    'tour date';

COMMENT ON COLUMN tour_available.ppt_no IS
    'passenger port tour number';

CREATE UNIQUE INDEX tour_available__idx ON
    tour_available (
        ppt_no
    ASC );

ALTER TABLE tour_available ADD CONSTRAINT port_tour_pk PRIMARY KEY ( tp_no );

ALTER TABLE tour_available
    ADD CONSTRAINT tour_available_nk UNIQUE ( tour_date,
                                              port_code,
                                              tour_no );

ALTER TABLE cabin
    ADD CONSTRAINT cabin_ship FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );

ALTER TABLE pass_port_tour
    ADD CONSTRAINT cruise_pass_port_tour FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_cruise FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE cruise_port
    ADD CONSTRAINT cruise_port_port FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE manifest
    ADD CONSTRAINT manifest_cabin FOREIGN KEY ( cabin_class )
        REFERENCES cabin ( cabin_class );

ALTER TABLE manifest
    ADD CONSTRAINT manifest_cruise FOREIGN KEY ( cruise_id )
        REFERENCES cruise ( cruise_id );

ALTER TABLE ship
    ADD CONSTRAINT operator_ship FOREIGN KEY ( op_id )
        REFERENCES operator ( op_id );

ALTER TABLE pass_port_tour
    ADD CONSTRAINT pass_pass_port_tour FOREIGN KEY ( pass_id )
        REFERENCES passenger ( pass_id );

ALTER TABLE passenger
    ADD CONSTRAINT pass_spouse FOREIGN KEY ( pass_id1 )
        REFERENCES passenger ( pass_id );

ALTER TABLE passenger
    ADD CONSTRAINT passenger_language FOREIGN KEY ( lang_code )
        REFERENCES language ( lang_code );

ALTER TABLE tour_available
    ADD CONSTRAINT port_port_tour FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE temperature
    ADD CONSTRAINT port_temperature FOREIGN KEY ( port_code )
        REFERENCES port ( port_code );

ALTER TABLE port
    ADD CONSTRAINT relation_21 FOREIGN KEY ( country_code )
        REFERENCES country ( country_code );

ALTER TABLE manifest
    ADD CONSTRAINT relation_24 FOREIGN KEY ( pass_id )
        REFERENCES passenger ( pass_id );

ALTER TABLE tour_available
    ADD CONSTRAINT relation_28 FOREIGN KEY ( tour_no )
        REFERENCES tour ( tour_no );

ALTER TABLE cruise
    ADD CONSTRAINT ship_cruise FOREIGN KEY ( ship_code )
        REFERENCES ship ( ship_code );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             2
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

commit;
SPOOL off
set echo off
